name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: [self-hosted, production]

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Stop the server
      run: |
        npm run compose-down:prod
        docker image rm -f $(docker images -a | grep -v "postgres" | grep -v "redis" | grep -v "hasura/graphql-engine"  | awk 'NR>1 {print $1}')
    - name: build the whole app
      run: npm run build:all
    - name: start the server
      run: |
        npm run compose-up:prod
        echo "ğŸ†ğŸ†ğŸ† migrated successfully ğŸ†ğŸ†ğŸ†"
        echo "ğŸŒğŸŒğŸŒ server started successfully ğŸŒğŸŒğŸŒ"
      